# This is a config for E2B sandbox template.
# You can use template ID (p3uwnpdpnhme51vhagsd) or template name (vibe-nextjs-examine-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-examine-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-examine-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-examine-2')

team_id = "931db15e-8cb9-447b-99c8-3fcb62458778"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-examine-2"
template_id = "p3uwnpdpnhme51vhagsd"
